name       : libtorrent-rasterbar
version    : 1.0.6
release    : 2
source     :
    - https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_0_6/libtorrent-rasterbar-1.0.6.tar.gz : c97de804b77f44591801631aca3869567671df2d3e2afe7f5453d8db2478fd61
license    : BSD
summary    : libtorrent is a C++ implementation of the BitTorrent protocol.
description: |
    libtorrent is a C++ implementation of the BitTorrent protocol.
libsplit: no
builddeps  :
    - libboost-devel
    - libiconv-devel
setup      : |
    %configure --enable-python-binding --with-libiconv
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
