name       : libtorrent-rasterbar
version    : 1.0.10
release    : 5
source     :
    - https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_0_10/libtorrent-rasterbar-1.0.10.tar.gz : a865ceaca8b14acdd7be56d361ce4e64361299647e157ef7b3ac7e2812ca4c3e
license    : BSD
component  : programming
summary    : libtorrent is a C++ implementation of the BitTorrent protocol.
description: |
    libtorrent is a C++ implementation of the BitTorrent protocol.
builddeps  :
    - libboost-devel
    - libiconv-devel
setup      : |
    %configure \
        --enable-python-binding \
        --enable-shared \
        --disable-static \
        --with-libiconv
build      : |
    %make
install    : |
    %make_install
