name       : libtorrent-rasterbar
version    : 1.1.9
release    : 13
source     :
    - https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1_9/libtorrent-rasterbar-1.1.9.tar.gz : d57a0f5b159f58003c3031943463503f0d05ae3e428dd7c2383d1e35fb2c4e8c
license    : BSD-2-Clause
component  : programming
summary    : libtorrent is a C++ implementation of the BitTorrent protocol
description: |
    libtorrent is a C++ implementation of the BitTorrent protocol.
builddeps  :
    - libboost-devel
    - libiconv-devel
setup      : |
    %configure \
        --enable-python-binding \
        --enable-shared \
        --disable-static \
        --with-libiconv
build      : |
    %make
install    : |
    %make_install
