name       : libtorrent-rasterbar
version    : 1.2.5
release    : 20
source     :
    - https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_2_5/libtorrent-rasterbar-1.2.5.tar.gz : 84b79f85ffa4e4a5f434bf5c53b0d5a63dfea17b7623143caaa695faf61b2d1b
license    : BSD-2-Clause
component  : programming
summary    : libtorrent is a C++ implementation of the BitTorrent protocol
description: |
    libtorrent is a C++ implementation of the BitTorrent protocol.
builddeps  :
    - pkgconfig(python3)
    - libboost-devel
    - libiconv-devel
environment: |
    export PYTHON_EXECUTABLE=/usr/bin/python3
setup      : |
    %cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 -Dpython-bindings=on .
build      : |
    %make
install    : |
    %make_install
