name       : libtorrent-rasterbar
version    : 1.2.7
release    : 23
source     :
    - https://github.com/arvidn/libtorrent/releases/download/libtorrent_1_2_7/libtorrent-rasterbar-1.2.7.tar.gz : bc00069e65c0825cbe1eee5cdd26f94fcd9a621c4e7f791810b12fab64192f00
license    : BSD-2-Clause
component  : programming
summary    : libtorrent is a C++ implementation of the BitTorrent protocol
description: |
    libtorrent is a C++ implementation of the BitTorrent protocol.
builddeps  :
    - pkgconfig(python3)
    - libboost-devel
    - libiconv-devel
environment: |
    export PYTHON=/usr/bin/python3
setup      : |
    %configure --disable-static \
        --enable-python-binding \
        --with-boost-python=boost_python37
build      : |
    %make
install    : |
    %make_install
